import { safeJson, withSecurity, requestId, sameOriginAllowed, trimText, sha256Hex, fetchTimeout, MAX_BODY_BYTES, redactLog } from './lib/security.js';
import { upsertContact, addTags } from './lib/highlevel.js';
import { acquire, transition, STATES } from './lib/ledger.js';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const phoneOK=v=>/^\+?[0-9 ()-]{8,20}$/.test(v); const emailOK=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const publicHttpsURL=v=>{if(!v)return null;try{const u=new URL(v);return u.protocol==='https:'?u.toString():null}catch{return null}};
function fail(code,status,id,headers={}){return safeJson({ok:false,code,requestId:id},status,headers)}
function envReady(env){return env.ENVIRONMENT!=='production'||Boolean(env.GHL_PRIVATE_TOKEN&&env.GHL_LOCATION_ID&&env.TURNSTILE_SECRET_KEY&&env.IDEMPOTENCY_DB)}
async function verifyTurnstile(token,request,env,submissionId){
  if(!env.TURNSTILE_SECRET_KEY) throw Object.assign(new Error('CONFIGURATION_ERROR'),{kind:'config'});
  if(typeof token!=='string'||token.length<1||token.length>2048)return false;
  const f=new FormData();f.append('secret',env.TURNSTILE_SECRET_KEY);f.append('response',token);f.append('idempotency_key',submissionId);
  const ip=request.headers.get('CF-Connecting-IP');if(ip)f.append('remoteip',ip);
  let r;try{r=await fetchTimeout('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:f},6000)}catch(e){throw Object.assign(e,{kind:e?.name==='AbortError'?'timeout':'network'})}
  if(!r.ok)throw Object.assign(new Error('TURNSTILE_UPSTREAM'),{kind:'upstream'});let d;try{d=await r.json()}catch{throw Object.assign(new Error('TURNSTILE_JSON'),{kind:'invalid_json'})}
  const expectedHost=new URL(env.PUBLIC_ORIGIN||'https://drjovaniurologo.org').hostname;
  return d.success===true&&(!d.hostname||d.hostname===expectedHost)&&(!d.action||d.action==='lead_submit');
}
function parseLead(body){const allowed=new Set(['schema_version','submission_id','name','phone','email','city','reason','source','consent','privacy_notice_version','consent_timestamp','website','turnstile','cf-turnstile-response']);for(const k of Object.keys(body))if(!allowed.has(k))return null;return {name:trimText(body.name,80),phone:trimText(body.phone,20),email:trimText(body.email,120).toLowerCase(),city:trimText(body.city,40),reason:trimText(body.reason,120),source:trimText(body.source,120)}}
async function acceptLead(request,env){const rid=requestId(request);if(env.LEAD_SUBMISSIONS_ENABLED!=='true')return fail('SUBMISSIONS_DISABLED',503,rid);if(!envReady(env))return fail('CONFIGURATION_ERROR',503,rid);if(!sameOriginAllowed(request,env))return fail('SECURITY_REJECTION',403,rid);if(!request.headers.get('content-type')?.toLowerCase().startsWith('application/json'))return fail('UNSUPPORTED_MEDIA_TYPE',415,rid);const n=Number(request.headers.get('content-length')||0);if(n>MAX_BODY_BYTES)return fail('PAYLOAD_TOO_LARGE',413,rid);const text=await request.text();if(new TextEncoder().encode(text).length>MAX_BODY_BYTES)return fail('PAYLOAD_TOO_LARGE',413,rid);let body;try{body=JSON.parse(text)}catch{return fail('MALFORMED_JSON',400,rid)};if(body.website)return safeJson({ok:true,submissionId:body.submission_id||'',requestId:rid},201);
  const lead=parseLead(body);if(!lead||body.schema_version!=='1'||!uuid.test(body.submission_id||'')||lead.name.length<3||!phoneOK(lead.phone)||!emailOK(lead.email)||!lead.city||!lead.reason||body.consent!==true||!body.privacy_notice_version||!body.consent_timestamp)return fail('VALIDATION_ERROR',422,rid);
  const canonical=JSON.stringify({v:'1',name:lead.name,phone:lead.phone,email:lead.email,city:lead.city,reason:lead.reason,source:lead.source,consent:true,privacy:body.privacy_notice_version});const hash=await sha256Hex(canonical);const now=new Date().toISOString();const lock=await acquire(env.IDEMPOTENCY_DB,body.submission_id,hash,now);if(!lock.ok)return fail(lock.reason==='payload_conflict'?'IDEMPOTENCY_CONFLICT':lock.reason==='storage_unconfigured'||lock.reason==='storage_error'?'STORAGE_UNAVAILABLE':'REQUEST_IN_FLIGHT',lock.reason?.startsWith('storage')?503:409,rid);if(lock.completed)return safeJson({ok:true,submissionId:body.submission_id,requestId:rid},200);
  try{await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.SECURITY_VERIFIED);if(!(await verifyTurnstile(body.turnstile||body['cf-turnstile-response']||'',request,env,body.submission_id))){await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.FAILED_TERMINAL);return fail('SECURITY_REJECTION',403,rid)}await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.TURNSTILE_VERIFIED);
    if(env.LEAD_RATE_LIMITER){const key=(await sha256Hex(lead.phone.replace(/\D/g,''))).slice(0,32);const rl=await env.LEAD_RATE_LIMITER.limit({key:`lead:${key}`});if(!rl.success)return fail('LOCAL_RATE_LIMIT',429,rid,{'retry-after':'60'});}
    const c=await upsertContact(lead,env);await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.CRM_CONTACT_UPSERTED,{contact_id:c.contactId});await addTags(c.contactId,['web-uroclinic','solicitud-horario'],env);await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.CRM_TAGGED);
    // Secondary channels intentionally do not determine persistence success.
    await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.SECONDARY_NOTIFICATIONS_PROCESSED);await transition(env.IDEMPOTENCY_DB,body.submission_id,STATES.COMPLETED);console.log(JSON.stringify(redactLog({event:'lead_completed',requestId:rid,submissionId:body.submission_id.slice(0,8),state:'COMPLETED'})));return safeJson({ok:true,submissionId:body.submission_id,requestId:rid},201);
  }catch(e){try{await transition(env.IDEMPOTENCY_DB,body.submission_id,e?.kind==='http'&&e.status>=400&&e.status<500&&e.status!==429?STATES.FAILED_TERMINAL:STATES.FAILED_RETRYABLE)}catch{}console.error(JSON.stringify(redactLog({event:'lead_failed',requestId:rid,kind:e?.kind||'unknown',status:e?.status||0})));if(e?.kind==='timeout')return fail('UPSTREAM_TIMEOUT',504,rid);if(e?.kind==='invalid_json'||e?.kind==='schema')return fail('BAD_UPSTREAM_RESPONSE',502,rid);if(e?.status===429)return fail('CRM_UNAVAILABLE',503,rid,e.retryAfter?{'retry-after':e.retryAfter}:{});return fail('CRM_UNAVAILABLE',503,rid);}
}
async function aiAssist(request,env){const rid=requestId(request);if(!env.ADMIN_API_KEY||request.headers.get('x-admin-key')!==env.ADMIN_API_KEY)return fail('UNAUTHORIZED',401,rid);return fail('ADMIN_AI_DISABLED_PENDING_SEPARATE_HARDENING',503,rid)}
export default {async fetch(request,env){const u=new URL(request.url);if(u.hostname==='www.drjovaniurologo.org'){u.hostname='drjovaniurologo.org';return withSecurity(Response.redirect(u.toString(),308));}if(u.pathname==='/api/health'){if(request.method!=='GET')return fail('METHOD_NOT_ALLOWED',405,requestId(request),{allow:'GET'});return safeJson({ok:true,service:'uroclinic',environment:env.ENVIRONMENT||'unknown',version:'2.6.0-111x'});}if(u.pathname==='/api/public-config'&&request.method==='GET')return safeJson({turnstileSiteKey:env.TURNSTILE_SITE_KEY||null,bookingUrl:publicHttpsURL(env.GHL_BOOKING_URL)});if(u.pathname==='/api/lead'){if(request.method!=='POST')return fail('METHOD_NOT_ALLOWED',405,requestId(request),{allow:'POST'});return acceptLead(request,env)}if(u.pathname==='/api/admin/ai'){if(request.method!=='POST')return fail('METHOD_NOT_ALLOWED',405,requestId(request),{allow:'POST'});return aiAssist(request,env)}if(u.pathname.startsWith('/api/'))return fail('NOT_FOUND',404,requestId(request));const r=await env.ASSETS.fetch(request);return withSecurity(r);}};
export {acceptLead,verifyTurnstile,parseLead};
